pipelines:
  default:
    - step:
        image: lmlt/alpine-aws-node
        caches:
          - node
          - docker
        script:
          - yarn install
          - yarn generate
          - aws s3 sync --delete dist/ s3://decoralyte --cache-control "public, max-age=14400"

