image: noxan/docker-node-awscli-yarn

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - yarn install
            - yarn generate
            - aws s3 sync dist/ s3://decoralyte --cache-control "public, max-age=14400" --delete
